version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./pkg:/app/pkg
    environment:
      - DSN=
      - TUYA_ACCESS_ID=
      - TUYA_ACCESS_KEY=
      - TUYA_APP_NAME=
      - GIN_MODE=
